insert into wn.ptr (ptr,name,field,pos) values ('!' ,'Antonym','lexical',              'lexical' ,'nvj');
insert into wn.ptr (ptr,name,field,pos) values ('@' ,'Hypernym',                       'semantic','nv');
insert into wn.ptr (ptr,name,field,pos) values ('@i','Instance Hypernym',              'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values ('~' ,'Hyponym',                        'semantic','nv');
insert into wn.ptr (ptr,name,field,pos) values ('~i','Instance Hyponym',               'semantic','nv');
insert into wn.ptr (ptr,name,field,pos) values ('#m','Member holonym',                 'semantic','nv');
insert into wn.ptr (ptr,name,field,pos) values ('#s','Substance holonym',              'semantic','nv');
insert into wn.ptr (ptr,name,field,pos) values ('#p','Part holonym',                   'semantic','nv');
insert into wn.ptr (ptr,name,field,pos) values ('%m','Member meronym',                 'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values ('%s','Substance meronym',              'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values ('%p','Part meronym',                   'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values ('=' ,'Attribute',                      'semantic','nj');
insert into wn.ptr (ptr,name,field,pos) values ('=+','Derivationally related form',    'lexical' ,'nv');
insert into wn.ptr (ptr,name,field,pos) values (';c','Domain of synset - TOPIC',       'semantic','nvja');
insert into wn.ptr (ptr,name,field,pos) values ('-c','Member of this domain - TOPIC',  'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values (';r','Domain of synset - REGION',      'semantic','nvja');
insert into wn.ptr (ptr,name,field,pos) values ('-r','Member of this domain - REGION', 'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values (';u','Domain of synset - USAGE',       'semantic','nvja');
insert into wn.ptr (ptr,name,field,pos) values ('-u','Member of this domain - USAGE',  'semantic','n');
insert into wn.ptr (ptr,name,field,pos) values ('*' ,'Entailment',                     'semantic','v');
insert into wn.ptr (ptr,name,field,pos) values ('>' ,'Cause',                          'semantic','v');
insert into wn.ptr (ptr,name,field,pos) values ('^' ,'Also see',                       'lexical' ,'vj');
insert into wn.ptr (ptr,name,field,pos) values ('$' ,'Verb Group',                     'semantic','v');
insert into wn.ptr (ptr,name,field,pos) values ('\' ,'Pertainym (pertains to noun)',   'lexical' ,'j');
insert into wn.ptr (ptr,name,field,pos) values ('-\','Pertainym (derived from adj)',   'lexical' ,'a');
insert into wn.ptr (ptr,name,field,pos) values ('&' ,'Similar to',                     'semantic','j');
insert into wn.ptr (ptr,name,field,pos) values ('<' ,'Participle of verb',             'lexical' ,'j');
