insert into wn.rel (ptr,name,type,pos) values ('!' ,'Antonym','lexical',              'lexical' ,'nvj');
insert into wn.rel (ptr,name,type,pos) values ('@' ,'Hypernym',                       'symantic','nv');
insert into wn.rel (ptr,name,type,pos) values ('@i','Instance Hypernym',              'symantic','n');
insert into wn.rel (ptr,name,type,pos) values ('~' ,'Hyponym',                        'symantic','nv');
insert into wn.rel (ptr,name,type,pos) values ('~i','Instance Hyponym',               'symantic','nv');
insert into wn.rel (ptr,name,type,pos) values ('#m','Member holonym',                 'symantic','nv');
insert into wn.rel (ptr,name,type,pos) values ('#s','Substance holonym',              'symantic','nv');
insert into wn.rel (ptr,name,type,pos) values ('#p','Part holonym',                   'symantic','nv');
insert into wn.rel (ptr,name,type,pos) values ('%m','Member meronym',                 'symantic','n');
insert into wn.rel (ptr,name,type,pos) values ('%s','Substance meronym',              'symantic','n');
insert into wn.rel (ptr,name,type,pos) values ('%p','Part meronym',                   'symantic','n');
insert into wn.rel (ptr,name,type,pos) values ('=' ,'Attribute',                      'symantic','nj');
insert into wn.rel (ptr,name,type,pos) values ('=+','Derivationally related form',    'lexical' ,'nv');
insert into wn.rel (ptr,name,type,pos) values (';c','Domain of synset - TOPIC',       'symantic','nvja');
insert into wn.rel (ptr,name,type,pos) values ('-c','Member of this domain - TOPIC',  'symantic','n');
insert into wn.rel (ptr,name,type,pos) values (';r','Domain of synset - REGION',      'symantic','nvja');
insert into wn.rel (ptr,name,type,pos) values ('-r','Member of this domain - REGION', 'symantic','n');
insert into wn.rel (ptr,name,type,pos) values (';u','Domain of synset - USAGE',       'symantic','nvja');
insert into wn.rel (ptr,name,type,pos) values ('-u','Member of this domain - USAGE',  'symantic','n');
insert into wn.rel (ptr,name,type,pos) values ('*' ,'Entailment',                     'symantic','v');
insert into wn.rel (ptr,name,type,pos) values ('>' ,'Cause',                          'symantic','v');
insert into wn.rel (ptr,name,type,pos) values ('^' ,'Also see',                       'lexical' ,'vj');
insert into wn.rel (ptr,name,type,pos) values ('$' ,'Verb Group',                     'symantic','v');
insert into wn.rel (ptr,name,type,pos) values ('\' ,'Pertainym (pertains to noun)',   'lexical' ,'j');
insert into wn.rel (ptr,name,type,pos) values ('-\','Pertainym (derived from adj)',   'lexical' ,'a');
insert into wn.rel (ptr,name,type,pos) values ('&' ,'Similar to',                     'symantic','j');
insert into wn.rel (ptr,name,type,pos) values ('<' ,'Participle of verb',             'lexical' ,'j');
