insert into wn.cat (num, cat, ncat, name) values(00,''			,'adj.all'		,'all adjective clusters');
insert into wn.cat (num, cat, ncat, name) values(01,'pert'		,'adj.pert'		,'relational adjectives (pertainyms)');
insert into wn.cat (num, cat, ncat, name) values(02,''			,'adv.all'		,'all adverbs');
insert into wn.cat (num, cat, ncat, name) values(03,'Tops'		,'noun.Tops'		,'unique beginner for nouns');
insert into wn.cat (num, cat, ncat, name) values(04,'act'		,'noun.act'		,'nouns denoting acts or actions');
insert into wn.cat (num, cat, ncat, name) values(05,'animal'		,'noun.animal'		,'nouns denoting animals');
insert into wn.cat (num, cat, ncat, name) values(06,'artifact'		,'noun.artifact'	,'nouns denoting man-made objects');
insert into wn.cat (num, cat, ncat, name) values(07,'attribute'		,'noun.attribute'	,'nouns denoting attributes of people and objects');
insert into wn.cat (num, cat, ncat, name) values(08,'body'		,'noun.body'		,'nouns denoting body parts');
insert into wn.cat (num, cat, ncat, name) values(09,'cognition'		,'noun.cognition'	,'nouns denoting cognitive processes and contents');
insert into wn.cat (num, cat, ncat, name) values(10,'communication'	,'noun.communication'	,'nouns denoting communicative processes and contents');
insert into wn.cat (num, cat, ncat, name) values(11,'event'		,'noun.event'		,'nouns denoting natural events');
insert into wn.cat (num, cat, ncat, name) values(12,'feeling'		,'noun.feeling'		,'nouns denoting feelings and emotions');
insert into wn.cat (num, cat, ncat, name) values(13,'food'		,'noun.food'		,'nouns denoting foods and drinks');
insert into wn.cat (num, cat, ncat, name) values(14,'group'		,'noun.group'		,'nouns denoting groupings of people or objects');
insert into wn.cat (num, cat, ncat, name) values(15,'location'		,'noun.location'	,'nouns denoting spatial position');
insert into wn.cat (num, cat, ncat, name) values(16,'motive'		,'noun.motive''		,'nouns denoting goals');
insert into wn.cat (num, cat, ncat, name) values(17,'object'		,'noun.object'		,'nouns denoting natural objects (not man-made)');
insert into wn.cat (num, cat, ncat, name) values(18,'person'		,'noun.person'		,'nouns denoting people');
insert into wn.cat (num, cat, ncat, name) values(19,'phenomenon'	,'noun.phenomenon'	,'nouns denoting natural phenomena');
insert into wn.cat (num, cat, ncat, name) values(20,'plant'		,'noun.plant'		,'nouns denoting plants');
insert into wn.cat (num, cat, ncat, name) values(21,'possession'	,'noun.possession'	,'nouns denoting possession and transfer of possession');
insert into wn.cat (num, cat, ncat, name) values(22,'process'		,'noun.process'		,'nouns denoting natural processes');
insert into wn.cat (num, cat, ncat, name) values(23,'quantity'		,'noun.quantity'	,'nouns denoting quantities and units of measure');
insert into wn.cat (num, cat, ncat, name) values(24,'relation'		,'noun.relation'	,'nouns denoting relations between people or things or ideas');
insert into wn.cat (num, cat, ncat, name) values(25,'shape'		,'noun.shape'		,'nouns denoting two and three dimensional shapes');
insert into wn.cat (num, cat, ncat, name) values(26,'state'		,'noun.state'		,'nouns denoting stable states of affairs');
insert into wn.cat (num, cat, ncat, name) values(27,'substance'		,'noun.substance'	,'nouns denoting substances');
insert into wn.cat (num, cat, ncat, name) values(28,'time'		,'noun.time'		,'nouns denoting time and temporal relations');
insert into wn.cat (num, cat, ncat, name) values(29,'body'		,'verb.body'		,'verbs of grooming, dressing and bodily care');
insert into wn.cat (num, cat, ncat, name) values(30,'change'		,'verb.change'		,'verbs of size, temperature change, intensifying, etc.');
insert into wn.cat (num, cat, ncat, name) values(31,'cognition'		,'verb.cognition'	,'verbs of thinking, judging, analyzing, doubting');
insert into wn.cat (num, cat, ncat, name) values(32,'communicati'	,'verb.communication'	,'verbs of telling, asking, ordering, singing');
insert into wn.cat (num, cat, ncat, name) values(33,'competition'	,'verb.competition'	,'verbs of fighting, athletic activities');
insert into wn.cat (num, cat, ncat, name) values(34,'consumption'	,'verb.consumption'	,'verbs of eating and drinking');
insert into wn.cat (num, cat, ncat, name) values(35,'contact'		,'verb.contact'		,'verbs of touching, hitting, tying, digging');
insert into wn.cat (num, cat, ncat, name) values(36,'creation'		,'verb.creation'	,'verbs of sewing, baking, painting, performing');
insert into wn.cat (num, cat, ncat, name) values(37,'emotion'		,'verb.emotion'		,'verbs of feeling');
insert into wn.cat (num, cat, ncat, name) values(38,'motion'		,'verb.motion'		,'verbs of walking, flying, swimming');
insert into wn.cat (num, cat, ncat, name) values(39,'perception'	,'verb.perception'	,'verbs of seeing, hearing, feeling');
insert into wn.cat (num, cat, ncat, name) values(40,'possession'	,'verb.possession'	,'verbs of buying, selling, owning');
insert into wn.cat (num, cat, ncat, name) values(41,'social'		,'verb.social'		,'verbs of political and social activities and events');
insert into wn.cat (num, cat, ncat, name) values(42,'stative'		,'verb.stative'		,'verbs of being, having, spatial relations');
insert into wn.cat (num, cat, ncat, name) values(43,'weather'		,'verb.weather'		,'verbs of raining, snowing, thawing, thundering');
insert into wn.cat (num, cat, ncat, name) values(44,'ppl'		,'adj.ppl'		,'participial adjectives');
