insert into wn.ptr (ptr,name,reflex,field,pos) values ('!' ,'Antonym',                        '!' ,'lexical' ,'nvj');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('@' ,'Hypernym',                       '~' ,'semantic','nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('@i','Instance Hypernym',              '~i','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('~' ,'Hyponym',                        '@' ,'semantic','nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('~i','Instance Hyponym',               '@i','semantic','nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('#m','Member holonym',                 '%m','semantic','nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('#s','Substance holonym',              '%s','semantic','nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('#p','Part holonym',                   '%p','semantic','nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('%m','Member meronym',                 '#m','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('%s','Substance meronym',              '#s','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('%p','Part meronym',                   '#p','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('=' ,'Attribute',                      '=' ,'semantic','nj');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('+' ,'Derivationally related form',    '+' ,'lexical' ,'nv');
insert into wn.ptr (ptr,name,reflex,field,pos) values (';c','Domain of synset - TOPIC',       '-c','semantic','nvja');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('-c','Member of this domain - TOPIC',  ';c','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values (';r','Domain of synset - REGION',      '-r','semantic','nvja');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('-r','Member of this domain - REGION', ';r','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values (';u','Domain of synset - USAGE',       '-u','semantic','nvja');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('-u','Member of this domain - USAGE',  ';u','semantic','n');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('*' ,'Entailment',                     ''  ,'semantic','v');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('>' ,'Cause',                          ''  ,'semantic','v');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('^' ,'Also see',                       ''  ,'lexical' ,'vj');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('$' ,'Verb Group',                     '$' ,'semantic','v');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('\' ,'Pertainym (pertains to noun)',   ''  ,'lexical' ,'j');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('-\','Pertainym (derived from adj)',   ''  ,'lexical' ,'a');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('&' ,'Similar to',                     '&' ,'semantic','j');
insert into wn.ptr (ptr,name,reflex,field,pos) values ('<' ,'Participle of verb',             ''  ,'lexical' ,'j');
