insert into wn.cat (cat, pos, name, lname) values(00, 'a' ,''			,'all adjective clusters');
insert into wn.cat (cat, pos, name, lname) values(01, 'a' ,'pert'		,'relational adjectives (pertainyms)');
insert into wn.cat (cat, pos, name, lname) values(02, 'r' ,''			,'all adverbs');
insert into wn.cat (cat, pos, name, lname) values(03, 'n' ,'Tops'		,'unique beginner for nouns');
insert into wn.cat (cat, pos, name, lname) values(04, 'n' ,'act'		,'nouns denoting acts or actions');
insert into wn.cat (cat, pos, name, lname) values(05, 'n' ,'animal'		,'nouns denoting animals');
insert into wn.cat (cat, pos, name, lname) values(06, 'n' ,'artifact'		,'nouns denoting man-made objects');
insert into wn.cat (cat, pos, name, lname) values(07, 'n' ,'attribute'		,'nouns denoting attributes of people and objects');
insert into wn.cat (cat, pos, name, lname) values(08, 'n' ,'body'		,'nouns denoting body parts');
insert into wn.cat (cat, pos, name, lname) values(09, 'n' ,'cognition'		,'nouns denoting cognitive processes and contents');
insert into wn.cat (cat, pos, name, lname) values(10, 'n' ,'communication'	,'nouns denoting communicative processes and contents');
insert into wn.cat (cat, pos, name, lname) values(11, 'n' ,'event'		,'nouns denoting natural events');
insert into wn.cat (cat, pos, name, lname) values(12, 'n' ,'feeling'		,'nouns denoting feelings and emotions');
insert into wn.cat (cat, pos, name, lname) values(13, 'n' ,'food'		,'nouns denoting foods and drinks');
insert into wn.cat (cat, pos, name, lname) values(14, 'n' ,'group'		,'nouns denoting groupings of people or objects');
insert into wn.cat (cat, pos, name, lname) values(15, 'n' ,'location'		,'nouns denoting spatial position');
insert into wn.cat (cat, pos, name, lname) values(16, 'n' ,'motive'		,'nouns denoting goals');
insert into wn.cat (cat, pos, name, lname) values(17, 'n' ,'object'		,'nouns denoting natural objects (not man-made)');
insert into wn.cat (cat, pos, name, lname) values(18, 'n' ,'person'		,'nouns denoting people');
insert into wn.cat (cat, pos, name, lname) values(19, 'n' ,'phenomenon'		,'nouns denoting natural phenomena');
insert into wn.cat (cat, pos, name, lname) values(20, 'n' ,'plant'		,'nouns denoting plants');
insert into wn.cat (cat, pos, name, lname) values(21, 'n' ,'possession'		,'nouns denoting possession and transfer of possession');
insert into wn.cat (cat, pos, name, lname) values(22, 'n' ,'process'		,'nouns denoting natural processes');
insert into wn.cat (cat, pos, name, lname) values(23, 'n' ,'quantity'		,'nouns denoting quantities and units of measure');
insert into wn.cat (cat, pos, name, lname) values(24, 'n' ,'relation'		,'nouns denoting relations between people or things or ideas');
insert into wn.cat (cat, pos, name, lname) values(25, 'n' ,'shape'		,'nouns denoting two and three dimensional shapes');
insert into wn.cat (cat, pos, name, lname) values(26, 'n' ,'state'		,'nouns denoting stable states of affairs');
insert into wn.cat (cat, pos, name, lname) values(27, 'n' ,'substance'		,'nouns denoting substances');
insert into wn.cat (cat, pos, name, lname) values(28, 'n' ,'time'		,'nouns denoting time and temporal relations');
insert into wn.cat (cat, pos, name, lname) values(29, 'v' ,'body'		,'verbs of grooming, dressing and bodily care');
insert into wn.cat (cat, pos, name, lname) values(30, 'v' ,'change'		,'verbs of size, temperature change, intensifying, etc.');
insert into wn.cat (cat, pos, name, lname) values(31, 'v' ,'cognition'		,'verbs of thinking, judging, analyzing, doubting');
insert into wn.cat (cat, pos, name, lname) values(32, 'v' ,'communication'	,'verbs of telling, asking, ordering, singing');
insert into wn.cat (cat, pos, name, lname) values(33, 'v' ,'competition'	,'verbs of fighting, athletic activities');
insert into wn.cat (cat, pos, name, lname) values(34, 'v' ,'consumption'	,'verbs of eating and drinking');
insert into wn.cat (cat, pos, name, lname) values(35, 'v' ,'contact'		,'verbs of touching, hitting, tying, digging');
insert into wn.cat (cat, pos, name, lname) values(36, 'v' ,'creation'		,'verbs of sewing, baking, painting, performing');
insert into wn.cat (cat, pos, name, lname) values(37, 'v' ,'emotion'		,'verbs of feeling');
insert into wn.cat (cat, pos, name, lname) values(38, 'v' ,'motion'		,'verbs of walking, flying, swimming');
insert into wn.cat (cat, pos, name, lname) values(39, 'v' ,'perception'		,'verbs of seeing, hearing, feeling');
insert into wn.cat (cat, pos, name, lname) values(40, 'v' ,'possession'		,'verbs of buying, selling, owning');
insert into wn.cat (cat, pos, name, lname) values(41, 'v' ,'social'		,'verbs of political and social activities and events');
insert into wn.cat (cat, pos, name, lname) values(42, 'v' ,'stative'		,'verbs of being, having, spatial relations');
insert into wn.cat (cat, pos, name, lname) values(43, 'v' ,'weather'		,'verbs of raining, snowing, thawing, thundering');
insert into wn.cat (cat, pos, name, lname) values(44, 'a' ,'ppl'		,'participial adjectives');
